version: "2.4"

services:
  iac-ocean-blue:
    build:
      context: .
      target: dev
      dockerfile: ./blue.Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      # - ./build/.:/terraform/app
      - ./.jenkins_vol:/var/jenkins_home
      - ./.sock:/var/run/docker.sock
    env_file:
      - ./.env/app.env
    stdin_open: true
    tty: true

  # TODO VERIFY BELOW SERVICES IF NEEDED, FOR NOW NOT REQUIRED SERVICE ABOVE WILL CATER FOR ALL REQUIREMENTS
  # > REMOVE WHEN PRODUCTION CODE IS RELEASED 

  # iac-jenkins:
  #     build:
  #       context: .
  #       target: dev
  #       dockerfile: ./jenkins.Dockerfile
  #     ports:
  #       - 8080:8080
  #     volumes:
  #       - ./build/.:/terraform/app
  #       - ./cicd/.:/var/jenkins_home
  #     env_file:
  #       - ./.env/app.development.env
  #     # stdin_open: true
  #     tty: true
