version: "2.4"

services:
  ocean-blue:
    build:
      context: .
      target: dev
      dockerfile: ./blue.Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.jenkins_vol:/var/jenkins_home
    env_file:
      - ./.env/app.env
    stdin_open: true
    tty: true
